In [10]:
#!pip install numpy
import numpy as np

# Create an array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

# Create an array of zeros
zeros_arr = np.zeros(5)  # Create an array with 5 zeros
print(zeros_arr)  # Output: [0. 0. 0. 0. 0.]

# Create an array of ones
ones_arr = np.ones((2, 3))  # Create a 2D array with ones
print(ones_arr)  # Output: [[1. 1. 1.]
                  #        [1. 1. 1.]]


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
import pandas as pd

# Creating a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

# Display the DataFrame
print(df)



      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [17]:
conda install anaconda::pandas


Channels:
Note: you may need to restart the kernel to use updated packages.

 - defaults
 - anaconda
Platform: win-64
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\suhashr\AppData\Local\anaconda3

  added / updated specs:
    - anaconda::pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-2.1.1               |  py311hf62ec03_0        14.7 MB  anaconda
    ------------------------------------------------------------
                                           Total:        14.7 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  pandas             pkgs/main::pandas-2.1.4-py311hf62ec03~ --> anaconda::pandas-2.1.1-py311hf62ec03_0 



Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
